export PATH=$HOME/local/bin:$PATH
export PATH=$HOME/local/bin:$PATH

# Enable tab completion
source ~/.git-completion.bash

# colors
green="\[\033[0;32m\]"
blue="\[\033[0;34m\]"
red="\[\033[0;31m\]"
reset="\[\033[0m\]"

#Change command prompt
source ~/.git-prompt.sh
export GIT_PS1_SHOWDIRTYSTATE=1

export PS1="$red\u$green\$(__git_ps1)$blue \W $ $reset"

#You can setup your favorite editor to open from terminal
#export PATH=$PATH:/Applications/Sublime\ Text.app/Contents/SharedSupport/bin
